import { AiError, LanguageModel } from "@effect/ai"
import { OpenAiClient, OpenAiLanguageModel } from "@effect/ai-openai"
import { HttpClient, HttpClientRequest } from "@effect/platform"
import { Effect, Either, FiberRef, Option, Redacted, Stream } from "effect"
import { CurrentModelCallPolicy, CurrentPromptCacheKey, foldStreamParts } from "@xandreed/engine"
import { OpenAiCodexWebSocketHttpClient } from "./openAiCodexWebSocket.js"

export const OPENAI_CODEX_API_URL = "https://chatgpt.com/backend-api/codex"

type Json = Record<string, unknown>

const record = (value: unknown): Json =>
  typeof value === "object" && value !== null ? value as Json : {}

const instructionText = (message: unknown): ReadonlyArray<string> => {
  const value = record(message)
  if (value["role"] !== "developer" && value["role"] !== "system") return []
  const content = value["content"]
  if (typeof content === "string") return [content]
  if (!Array.isArray(content)) return []
  return content.flatMap((part) => {
    const item = record(part)
    return typeof item["text"] === "string" ? [item["text"]] : []
  })
}

/** Translate the standard Responses request into the Codex subscription dialect. */
export const toOpenAiCodexRequestBody = (
  body: unknown,
  reasoningEffort?: "low" | "medium" | "high" | "xhigh" | "max",
): Json => {
  const value = record(body)
  const input = Array.isArray(value["input"]) ? value["input"] : []
  const instructions = input.flatMap(instructionText).join("\n\n")
  const conversationalInput = input.filter((message) => instructionText(message).length === 0)
  const configuredText = record(value["text"])
  // ChatGPT's subscription endpoint is not the public Responses API and
  // rejects this otherwise-standard field. Agent timeouts/step limits remain
  // the execution bound; Pi's working adapter likewise omits it.
  const supported = Object.fromEntries(
    Object.entries(value).filter(([key]) => key !== "max_output_tokens"),
  )
  return {
    ...supported,
    store: false,
    stream: true,
    instructions: instructions.length > 0 ? instructions : "You are a helpful assistant.",
    input: conversationalInput,
    // The subscription dialect accepts verbosity but rejects/derails the
    // public API's nested text.format object generated by the SDK.
    text: { verbosity: configuredText["verbosity"] ?? "low" },
    include: ["reasoning.encrypted_content"],
    tool_choice: value["tool_choice"] ?? "auto",
    parallel_tool_calls: value["parallel_tool_calls"] ?? true,
    ...(reasoningEffort === undefined
      ? {}
      : { reasoning: { ...record(value["reasoning"]), effort: reasoningEffort, summary: "auto" } }),
  }
}

const transformRequest = (
  accountId: string,
  reasoningEffort?: "low" | "medium" | "high" | "xhigh" | "max",
) => (request: HttpClientRequest.HttpClientRequest): HttpClientRequest.HttpClientRequest => {
  const withHeaders = request.pipe(
    HttpClientRequest.setHeaders({
      "chatgpt-account-id": accountId,
      // This adapter uses Pi's registered OAuth client. The backend keys
      // model entitlement to that client/originator pair, so this header is
      // part of the protocol (Luna otherwise returns a misleading 404).
      originator: "pi",
      "OpenAI-Beta": "responses=experimental",
      accept: "text/event-stream",
    }),
  )
  if (request.body._tag !== "Uint8Array") return withHeaders
  const encodedBody = request.body.body
  return Option.match(
    Either.getRight(Either.try(() => JSON.parse(new TextDecoder().decode(encodedBody)) as unknown)),
    {
      onNone: () => withHeaders,
      onSome: (decoded) => HttpClientRequest.bodyUnsafeJson(
        withHeaders,
        toOpenAiCodexRequestBody(decoded, reasoningEffort),
      ),
    },
  )
}

const responseStatus = (error: unknown): number | undefined => {
  const value = record(error)
  const response = record(value["response"])
  return typeof response["status"] === "number" ? response["status"] : undefined
}

export const mapOpenAiCodexError = (model: string, error: unknown): unknown =>
  responseStatus(error) === 404
    ? new AiError.MalformedInput({
        module: "OpenAiCodex",
        method: "responses",
        description: `model ${model} is not available to the configured ChatGPT subscription account`,
        cause: error,
      })
    : responseStatus(error) === 200
      ? new AiError.MalformedOutput({
          module: "OpenAiCodex",
          method: "responses",
          description: `the ${model} subscription stream returned a rejected or incompatible event`,
          cause: error,
        })
      : error

export const makeOpenAiCodexLanguageModel = (args: {
  readonly model: string
  readonly accessToken: Redacted.Redacted<string>
  readonly accountId: string
}) =>
  Effect.all({
    cacheKey: FiberRef.get(CurrentPromptCacheKey),
    policy: FiberRef.get(CurrentModelCallPolicy),
  }).pipe(
    Effect.flatMap(({ cacheKey, policy }) =>
      OpenAiClient.make({
        apiKey: args.accessToken,
        apiUrl: OPENAI_CODEX_API_URL,
        transformClient: () => OpenAiCodexWebSocketHttpClient.pipe(
          // Replacing the transport also replaces OpenAiClient's underlying
          // request pipeline, so reproduce its base URL + bearer steps here.
          HttpClient.mapRequest((request) =>
            transformRequest(
              args.accountId,
              Option.getOrUndefined(Option.map(policy, (value) => value.effort)),
            )(
              request.pipe(
                HttpClientRequest.prependUrl(OPENAI_CODEX_API_URL),
                HttpClientRequest.bearerToken(args.accessToken),
              ),
            ),
          ),
        ),
      }).pipe(
        Effect.flatMap((client) =>
          OpenAiLanguageModel.make({
            model: args.model,
            config: {
              strict: false,
              store: false,
              prompt_cache_key: Option.getOrElse(cacheKey, () => "efferent"),
              text: { verbosity: "low" },
              ...Option.match(policy, {
                onNone: () => ({}),
                onSome: (value) => ({
                  ...(value.maxOutputTokens === undefined
                    ? {}
                    : { max_output_tokens: value.maxOutputTokens }),
                  reasoning: {
                    // @effect/ai-openai's generated union predates xhigh/max;
                    // transformRequest restores the exact effort on the wire.
                    effort: value.effort === "xhigh" || value.effort === "max" ? "high" : value.effort,
                    summary: "auto" as const,
                  },
                }),
              }),
            },
          }).pipe(Effect.provideService(OpenAiClient.OpenAiClient, client)),
        ),
        // The ChatGPT subscription endpoint is stream-only. Expose the full
        // LanguageModel port by deriving settled calls from that same stream,
        // so non-streaming use cases do not accidentally send stream:false.
        Effect.map((streaming) => {
          const streamText = ((options: unknown) =>
            streaming.streamText(options as never).pipe(
              Stream.mapError((error) => mapOpenAiCodexError(args.model, error)),
            )) as LanguageModel.Service["streamText"]
          return {
            ...streaming,
            streamText,
            generateText: ((options: unknown) =>
              foldStreamParts(streamText(options as never), () => Effect.void).pipe(
                Effect.map((turn) => new LanguageModel.GenerateTextResponse(turn.content as never)),
              )) as LanguageModel.Service["generateText"],
          } satisfies LanguageModel.Service
        }),
      ),
    ),
  )
