#!/usr/bin/env bun
/**
 * Bundle @xandreed/code → packages/code/dist/efferent.js.
 *
 * Uses the Bun.build API (not the `bun build` CLI) because the TUI's Solid JSX
 * (`packages/code/src/cli/*.tsx`) needs the OpenTUI Solid babel transform,
 * and the CLI `bun build` does NOT honor bunfig `preload` plugins — only the
 * programmatic `plugins` array applies at build time. `createSolidTransformPlugin`
 * also performs solid-js's server→client entry swap so the bundled reactive
 * runtime is the universal/client build.
 *
 * `@opentui/core` is the one runtime dependency left EXTERNAL: it dlopen()s its
 * native Zig lib (`@opentui/core-<platform>/libopentui.so`) via a path resolved
 * relative to its own package location, which only works when it resolves from
 * node_modules at runtime. Everything else (@opentui/solid, solid-js, effect,
 * @effect/*) is inlined, so the dist stays a single self-contained file plus
 * that one native dependency.
 *
 * Path-independent (resolves from the script location), so it runs identically
 * from the repo root (`bun run build`) or from packages/code (`prepublishOnly`).
 */
import { join } from "node:path"

const root = join(import.meta.dir, "..")

/**
 * Stub out the provider tokenizer packages. `@effect/ai-anthropic` /
 * `@effect/ai-openai` statically import `@anthropic-ai/tokenizer` /
 * `gpt-tokenizer` for their optional `Tokenizer` service, which efferent never
 * uses (token counts come from provider usage metadata). Left in, they cost
 * ~3MB of inlined BPE vocab AND break the published bundle two ways: tiktoken's
 * CJS shim bakes this machine's absolute build path into the artifact (a
 * privacy leak), and its wasm loader readFileSync()s at module-init — on a
 * machine without tiktoken in node_modules that's a crash at startup.
 */
const tokenizerStub: Bun.BunPlugin = {
  name: "stub-tokenizers",
  setup(build) {
    build.onResolve({ filter: /^@anthropic-ai\/tokenizer$|^gpt-tokenizer$/ }, (args) => ({
      path: args.path,
      namespace: "tokenizer-stub",
    }))
    build.onLoad({ filter: /.*/, namespace: "tokenizer-stub" }, () => ({
      contents: `const unavailable = () => { throw new Error("tokenizers are not bundled with efferent (the CLI never tokenizes locally)") }
export const getTokenizer = unavailable
export const countTokens = unavailable
export const encode = unavailable
export const decode = unavailable
export default { getTokenizer: unavailable, countTokens: unavailable, encode: unavailable, decode: unavailable }
`,
      loader: "js",
    }))
  },
}

const result = await Bun.build({
  entrypoints: [join(root, "packages/code/src/main.ts")],
  outdir: join(root, "packages/code/dist"),
  naming: "efferent.js",
  target: "bun",
  external: ["@opentui/core"],
  plugins: [
    tokenizerStub,
    (await import("@opentui/solid/bun-plugin")).createSolidTransformPlugin(),
  ],
})

if (!result.success) {
  console.error("efferent build failed:")
  for (const log of result.logs) console.error(log)
  process.exit(1)
}

/**
 * Emit the `code` bin shim next to the bundle. It's a tiny, dependency-free
 * forwarder (no second full bundle): it injects `--code` into argv (so the
 * shared CLI selects the in-process driver + `variant: "code"`) and imports the
 * one real bundle. A dedicated entry is needed because Bun resolves a symlinked
 * bin's `argv[1]` to the bundle path, so name-sniffing can't detect a `code`
 * invocation (see packages/code/src/code.ts).
 *
 * TODO(release): the bin name `code` collides with the VS Code CLI — confirm
 * the published name before cutting a release.
 */
const { writeFileSync } = await import("node:fs")
writeFileSync(
  join(root, "packages/code/dist/code.js"),
  `#!/usr/bin/env bun
// efferent — the \`code\` bin shim. Forces the focused single-fleet coder
// (\`--code\`) and runs the shared bundle. Generated by scripts/build.ts.
if (!process.argv.includes("--code")) process.argv.splice(2, 0, "--code")
await import("./efferent.js")
`,
  { mode: 0o755 },
)

console.error(
  `efferent: bundled ${result.outputs.length} output → packages/code/dist/efferent.js (+ dist/code.js shim)`,
)
