import { cpSync, existsSync, mkdirSync, rmSync, writeFileSync } from "node:fs"
import { dirname, join } from "node:path"
import { Effect, Either, Option, Ref, Schema } from "effect"
import type { LanguageModel } from "@effect/ai"
import {
  BaselineFile,
  fingerprintFindings,
  gatesFromConfig,
  loadConfig,
  TsProjectCachedLive,
  vendoredPackFiles,
} from "@xandreed/foundry"
import { ConversationStore, FileSystem, runAgent, Shell } from "@xandreed/engine"
import type { AgentConfig, ConversationId } from "@xandreed/engine"
import { loadWorkspaceRules } from "../forge/session.js"
import { makeCommandGate } from "../gates/commandGate.js"
import { makeSmithCodingHandlers } from "../implementor/codingToolkit.js"
import { BUNDLED_SKILLS_DIR, discoverSkills, renderSkillsBlock } from "../skills/skills.js"
import type { SmithEvent } from "../domain/SmithEvent.js"
import { profileSessionPrompt } from "./profilerPrompt.js"
import { ProfileProposal, profileToolkit } from "./toolkit.js"
import type { ProfileDryRun } from "./toolkit.js"

/** Where a proposal lives until the human locks it. */
export const PROFILE_DRAFT_DIR = ".efferent/profile-draft"
/** Where vendored + custom rule modules land at lock. */
export const PROFILE_GATES_DIR = ".efferent/gates"
const CHECK_TIMEOUT_MS = 30_000

export interface LockReport {
  readonly configPath: string
  readonly rules: number
  readonly grandfathered: number
  readonly checks: number
  readonly rulesFileWritten: boolean
}

export interface ProfileFailure {
  readonly error: string
  readonly message: string
}

/** The generated config module — DATA in the default export, the plugged
 *  rule modules through the code channel. Regenerated (never rewritten) for
 *  the draft dir and again at lock with the final import path. */
export const renderConfigSource = (
  proposal: ProfileProposal,
  options: { readonly gatesImport: Option.Option<string>; readonly typecheck: boolean },
): string => {
  const rules = proposal.rules.map((entry) => ({
    rule: entry.rule,
    ...(entry.include !== undefined ? { include: entry.include } : {}),
    ...(entry.exclude !== undefined ? { exclude: entry.exclude } : {}),
  }))
  const data = {
    tsconfig: "tsconfig.json",
    rules,
    ...(proposal.boundaries.length > 0 ? { boundaries: { layers: proposal.boundaries } } : {}),
    ...(proposal.checks.length > 0 ? { checks: proposal.checks } : {}),
    typecheck: options.typecheck,
  }
  return [
    "// Generated by `smith profile` — PROJECT-OWNED. Edit freely; the rules",
    "// under .efferent/gates/ are yours too.",
    ...Option.match(options.gatesImport, {
      onNone: () => [] as ReadonlyArray<string>,
      onSome: (path) => [
        `import { rules } from "${path}"`,
        "",
        "export const customRules = rules",
      ],
    }),
    "",
    `export default ${JSON.stringify(data, null, 2)}`,
    "",
  ].join("\n")
}

/** `gates/index.ts` — merges every vendored pack + custom module into one
 *  pluggable `rules` array. */
const renderGatesIndex = (
  packs: ReadonlyArray<string>,
  customFiles: ReadonlyArray<string>,
): string =>
  [
    ...packs.map((name, i) => `import { rules as pack${i} } from "./${name}/rules.js"`),
    ...customFiles.map(
      (file, i) => `import { rules as custom${i} } from "./${file.replace(/\.ts$/, ".js")}"`,
    ),
    "",
    `export const rules = [${[
      ...packs.map((_, i) => `...pack${i}`),
      ...customFiles.map((_, i) => `...custom${i}`),
    ].join(", ")}]`,
    "",
  ].join("\n")

/** Materialize the proposal's rule modules + config under `dir`. */
const writeDraftFiles = (
  dir: string,
  proposal: ProfileProposal,
): Effect.Effect<void, ProfileFailure> =>
  Effect.gen(function* () {
    yield* Effect.sync(() => {
      rmSync(dir, { recursive: true, force: true })
      mkdirSync(join(dir, "gates"), { recursive: true })
    })
    yield* Effect.forEach(proposal.packs, (pack) =>
      vendoredPackFiles(pack).pipe(
        Effect.mapError((e) => ({ error: "UnknownPack", message: e.message })),
        Effect.map((files) =>
          files.forEach((file) => {
            const target = join(dir, "gates", file.path)
            mkdirSync(dirname(target), { recursive: true })
            writeFileSync(target, file.content)
          }),
        ),
      ),
    )
    yield* Effect.sync(() => {
      proposal.customRules.forEach((custom) => {
        writeFileSync(join(dir, "gates", custom.filename), custom.source)
      })
      const hasModules = proposal.packs.length > 0 || proposal.customRules.length > 0
      if (hasModules) {
        writeFileSync(
          join(dir, "gates", "index.ts"),
          renderGatesIndex(
            proposal.packs,
            proposal.customRules.map((custom) => custom.filename),
          ),
        )
      }
      writeFileSync(
        join(dir, "foundry.config.ts"),
        renderConfigSource(proposal, {
          gatesImport: hasModules ? Option.some("./gates/index.js") : Option.none(),
          // The draft dry-runs idioms + boundaries only — typecheck findings
          // would drown the counts; the LOCKED config arms typecheck.
          typecheck: false,
        }),
      )
      writeFileSync(
        join(dir, "draft.json"),
        JSON.stringify(Schema.encodeSync(ProfileProposal)(proposal), null, 2),
      )
    })
  })

/** Run the DRAFT's static gates over the real workspace — per-rule finding
 *  counts are the red-first analog for profiles: the human sees the blast
 *  radius ("no-let: 212 existing → grandfathered") BEFORE arming. */
const dryRun = (
  cwd: string,
  draftDir: string,
  proposal: ProfileProposal,
): Effect.Effect<ProfileDryRun, ProfileFailure> =>
  Effect.gen(function* () {
    const { config, registry } = yield* loadConfig(join(draftDir, "foundry.config.ts")).pipe(
      Effect.mapError((e) => ({ error: "InvalidProfile", message: e.message })),
    )
    const findings = yield* Effect.forEach(gatesFromConfig(config, registry), (gate) =>
      gate.run({ rootDir: cwd, files: [] }),
    ).pipe(
      Effect.map((all) => all.flat().filter((finding) => finding.severity === "error")),
      Effect.provide(TsProjectCachedLive),
      Effect.mapError((crash) => ({
        error: "DryRunFailed",
        message: `${crash.message} — the proposed gates cannot run on this workspace as drafted`,
      })),
    )
    const byRule = findings.reduce(
      (counts, finding) =>
        counts.set(String(finding.rule), (counts.get(String(finding.rule)) ?? 0) + 1),
      new Map<string, number>(),
    )
    const checks = yield* Effect.forEach(proposal.checks, (check) =>
      makeCommandGate({
        name: check.name,
        argv: ["bash", "-c", check.command],
        timeoutMs: CHECK_TIMEOUT_MS,
      })
        .run({ rootDir: cwd, files: [] })
        .pipe(
          Effect.map((found) => ({
            name: check.name,
            status: found.length === 0 ? ("green" as const) : ("red" as const),
          })),
          Effect.orElseSucceed(() => ({ name: check.name, status: "red" as const })),
        ),
    )
    return {
      draftDir,
      rules: proposal.rules.map((entry) => ({
        rule: entry.rule,
        findings: byRule.get(entry.rule) ?? 0,
      })),
      boundaryViolations: [...byRule.entries()]
        .filter(([rule]) => rule.startsWith("boundaries/"))
        .reduce((sum, [, count]) => sum + count, 0),
      checks,
      note: "existing findings are GRANDFATHERED at lock (only new code gates); a green check still guards regressions",
    }
  })

export type ProfileAgent = (
  conversationId: ConversationId,
  prompt: string,
  tools: {
    readonly propose: (
      params: typeof ProfileProposal.Encoded,
    ) => Effect.Effect<ProfileDryRun, ProfileFailure>
  },
) => Effect.Effect<void, unknown>

export interface ProfileSessionOptions {
  readonly unattended: boolean
  /** The scripted seam — tests and the twin drive the handlers without an LLM. */
  readonly agent?: ProfileAgent
}

export interface ProfileSession {
  readonly conversationId: ConversationId
  readonly send: (text: string) => Effect.Effect<Option.Option<ProfileDryRun>, unknown>
  readonly lock: Effect.Effect<LockReport, ProfileFailure>
}

export type ProfileServices =
  | ConversationStore
  | FileSystem
  | Shell
  | LanguageModel.LanguageModel

/**
 * The profile SETUP session — the refine pattern applied to the quality bar
 * itself: one persisted conversation, `propose_profile` as the ONLY write
 * (drafts under `.efferent/profile-draft/`, dry-run counts returned as
 * data), and only the human locks. Locking writes the config + vendored
 * rules + doctrine, mints the grandfathering baseline, and copies the
 * gate-rule-authoring skill into the workspace.
 */
export const makeProfileSession = (
  cwd: string,
  publish: (event: SmithEvent) => Effect.Effect<void>,
  options: ProfileSessionOptions,
): Effect.Effect<ProfileSession, never, ProfileServices> =>
  Effect.gen(function* () {
    const store = yield* ConversationStore
    const context = yield* Effect.context<ProfileServices>()
    const conversationId = yield* store.create(cwd).pipe(Effect.orDie)
    const draftRef = yield* Ref.make(Option.none<ProfileDryRun>())
    const draftDir = join(cwd, PROFILE_DRAFT_DIR)

    const propose = (params: typeof ProfileProposal.Encoded) =>
      Effect.gen(function* () {
        const proposal = yield* Schema.decodeUnknown(ProfileProposal)(params).pipe(
          Effect.mapError((e) => ({ error: "InvalidProposal", message: String(e) })),
        )
        yield* writeDraftFiles(draftDir, proposal)
        const result = yield* dryRun(cwd, draftDir, proposal)
        yield* Ref.set(draftRef, Option.some(result))
        return result
      })

    const coding = yield* makeSmithCodingHandlers(cwd).pipe(Effect.provide(context))
    const handlersLayer = profileToolkit.toLayer(
      profileToolkit.of({
        read_file: coding.read_file,
        grep: coding.grep,
        glob: coding.glob,
        ls: coding.ls,
        load_skill: coding.load_skill,
        propose_profile: propose,
      }),
    )

    const skillsBlock = renderSkillsBlock(yield* discoverSkills(cwd))
    const config: AgentConfig<(typeof profileToolkit)["tools"]> = {
      system: [
        profileSessionPrompt(cwd, { unattended: options.unattended }),
        ...(skillsBlock.length > 0 ? [skillsBlock] : []),
      ].join("\n\n"),
      toolkit: profileToolkit,
      maxSteps: 32,
      streaming: true,
    }

    const realAgent: ProfileAgent = (cid, prompt) =>
      runAgent(config, cid, prompt, {
        onEvent: (event) => publish({ type: "agent", event }),
      }).pipe(Effect.provide(handlersLayer), Effect.provide(context), Effect.asVoid)

    const agent = options.agent ?? realAgent

    return {
      conversationId,
      send: (text) =>
        agent(conversationId, text, { propose }).pipe(Effect.flatMap(() => Ref.get(draftRef))),
      lock: lockProfile(cwd).pipe(Effect.provide(context)),
    }
  })

/** `:lock` — arm the drafted profile. Refuses to overwrite an existing
 *  config; the rules file only lands when the workspace has none (an
 *  existing AGENTS.md wins the precedence chain). */
export const lockProfile = (
  cwd: string,
): Effect.Effect<LockReport, ProfileFailure, FileSystem> =>
  Effect.gen(function* () {
    const draftDir = join(cwd, PROFILE_DRAFT_DIR)
    const configPath = join(cwd, "foundry.config.ts")
    if (!existsSync(join(draftDir, "draft.json"))) {
      return yield* Effect.fail({
        error: "NoDraft",
        message: "nothing to lock — propose a profile first",
      })
    }
    if (existsSync(configPath)) {
      return yield* Effect.fail({
        error: "ConfigExists",
        message: `${configPath} already exists — this session never overwrites a committed profile; edit it directly or remove it first`,
      })
    }
    const fs = yield* FileSystem
    const proposal = yield* fs.read(join(draftDir, "draft.json")).pipe(
      Effect.flatMap(Schema.decodeUnknown(Schema.parseJson(ProfileProposal))),
      Effect.mapError((e) => ({ error: "CorruptDraft", message: String(e) })),
    )
    const hasModules = proposal.packs.length > 0 || proposal.customRules.length > 0
    const hasTsconfig = existsSync(join(cwd, "tsconfig.json"))

    yield* Effect.sync(() => {
      if (hasModules) {
        rmSync(join(cwd, PROFILE_GATES_DIR), { recursive: true, force: true })
        cpSync(join(draftDir, "gates"), join(cwd, PROFILE_GATES_DIR), { recursive: true })
      }
      writeFileSync(
        configPath,
        renderConfigSource(proposal, {
          gatesImport: hasModules
            ? Option.some(`./${PROFILE_GATES_DIR}/index.js`)
            : Option.none(),
          typecheck: hasTsconfig,
        }),
      )
    })

    // Doctrine prose — only when the workspace has no rules file at all.
    const existingRules = yield* loadWorkspaceRules(cwd)
    const rulesFileWritten = Option.isNone(existingRules) && proposal.doctrine.trim().length > 0
    yield* Effect.sync(() => {
      if (rulesFileWritten) {
        mkdirSync(join(cwd, ".efferent"), { recursive: true })
        writeFileSync(join(cwd, ".efferent", "rules.md"), `${proposal.doctrine.trim()}\n`)
      }
    })

    // The grandfathering baseline: every ERROR finding the FINAL config
    // produces right now is minted in — only NEW code gates from here on.
    // A config that cannot run must not lock (fail-closed).
    const { config, registry } = yield* loadConfig(configPath).pipe(
      Effect.mapError((e) => ({ error: "InvalidProfile", message: e.message })),
    )
    const findings = yield* Effect.forEach(gatesFromConfig(config, registry), (gate) =>
      gate.run({ rootDir: cwd, files: [] }),
    ).pipe(
      Effect.map((all) => all.flat().filter((finding) => finding.severity === "error")),
      Effect.provide(TsProjectCachedLive),
      Effect.mapError((crash) => ({ error: "LockFailed", message: crash.message })),
    )
    const fingerprinted = yield* fingerprintFindings(findings, cwd).pipe(
      Effect.mapError((e) => ({ error: "LockFailed", message: e.message })),
    )
    const fingerprints = [...new Set(fingerprinted.map((entry) => entry.fingerprint))]
    const baseline = yield* Schema.encode(Schema.parseJson(BaselineFile))({
      version: 1,
      fingerprints,
    }).pipe(Effect.mapError((e) => ({ error: "LockFailed", message: String(e) })))
    yield* Effect.sync(() => {
      mkdirSync(join(cwd, ".foundry"), { recursive: true })
      writeFileSync(join(cwd, ".foundry", "baseline.json"), `${baseline}\n`)
      // The authoring know-how travels WITH the workspace — the forge coder
      // can extend the profile later with the same knowledge.
      const skillSource = join(BUNDLED_SKILLS_DIR, "gate-rule-authoring.md")
      if (existsSync(skillSource)) {
        mkdirSync(join(cwd, ".efferent", "skills"), { recursive: true })
        cpSync(skillSource, join(cwd, ".efferent", "skills", "gate-rule-authoring.md"))
      }
      rmSync(draftDir, { recursive: true, force: true })
    })

    return {
      configPath,
      rules: proposal.rules.length,
      grandfathered: fingerprints.length,
      checks: proposal.checks.length,
      rulesFileWritten,
    }
  })

/**
 * `smith profile -p [--yes]`: one unattended proposal — the dry-run summary
 * prints to stdout; `--yes` locks. Exit: 0 = a draft exists (locked when
 * --yes) · 2 = no draft / error.
 */
export const runHeadlessProfile = (
  cwd: string,
  lockAfter: boolean,
): Effect.Effect<number, never, ProfileServices> =>
  Effect.gen(function* () {
    const session = yield* makeProfileSession(cwd, () => Effect.void, { unattended: true })
    const draft = yield* session
      .send(
        "Analyze this workspace and propose its quality profile — rules, boundaries where the layering is unambiguous, the project's own authoritative scripts as checks, and doctrine prose.",
      )
      .pipe(Effect.catchAll(() => Effect.succeed(Option.none<ProfileDryRun>())))
    if (Option.isNone(draft)) {
      console.error("the profiler produced no draft (no propose_profile call)")
      return 2
    }
    const summary = draft.value
    console.log("PROFILE DRAFT")
    summary.rules.forEach((rule) => {
      console.log(
        `  rule ${rule.rule}: ${rule.findings} existing finding(s) → grandfathered at lock`,
      )
    })
    if (summary.boundaryViolations > 0) {
      console.log(`  boundaries: ${summary.boundaryViolations} existing violation(s)`)
    }
    summary.checks.forEach((check) => {
      console.log(
        `  check ${check.name}: ${check.status}${check.status === "green" ? " (guards regressions)" : " (will gate until fixed)"}`,
      )
    })
    console.log(`  ${summary.note}`)
    if (!lockAfter) {
      console.log(`draft: ${summary.draftDir} — lock with: bun run smith profile -p --yes`)
      return 0
    }
    const outcome = yield* Effect.either(session.lock)
    return Either.match(outcome, {
      onLeft: (failure) => {
        console.error(`lock failed: ${failure.message}`)
        return 2
      },
      onRight: (report) => {
        console.log(
          `✓ profile ARMED: ${report.rules} rule(s) · ${report.grandfathered} grandfathered · ${report.checks} check(s) → ${report.configPath}`,
        )
        return 0
      },
    })
  })
